=== DeepskyLog/DeepskyLog/xml/languages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="lang">
		<xs:complexType>
			<xs:attribute name="code" type="xs:string" use="required"/>
			<xs:attribute name="name-en" type="xs:string" use="required"/>
			<xs:attribute name="name-fr" type="xs:string" use="optional"/>
			<xs:attribute name="name-de" type="xs:string" use="optional"/>
			<xs:attribute name="name-nl" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="languages">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lang" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DeepskyLog/DeepskyLog/lib/setup/language/languages.xml
<?xml version="1.0" encoding="UTF-8"?>
<languages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="languages.xsd">
<lang code="bg" name_en="Bulgarian" name_fr="Bulgare" name_de="Bulgarisch" name_nl="Bulgaars" name_sv="Bulgariska" />
<lang code="cs" name_en="Czech" name_fr="Tcheque" name_de="Tschechisch" name_nl="Tsjechisch" name_sv="Tjeckiska" />
<lang code="da" name_en="Danish" name_fr="Danois" name_de="Danisch" name_nl="Deens" name_sv="Danska" />
<lang code="de" name_en="German" name_fr="Allemand" name_de="Deutsch" name_nl="Duits" name_sv="Tyska" />
<lang code="el" name_en="Greek" name_fr="Grec" name_de="Griechisch" name_nl="Grieks" name_sv="Grekisk" />
<lang code="en" name_en="English" name_fr="Anglais" name_de="Englisch" name_nl="Engels" name_sv="Engelska" />
<lang code="eo" name_en="Esperanto" name_fr="Esperanto" name_de="Esperanto" name_nl="Esperanto" name_sv="Esperanto" />
<lang code="es" name_en="Spanish" name_fr="Espagnol" name_de="Spanisch" name_nl="Spaans" name_sv="Spanska" />
<lang code="fi" name_en="Finnish" name_fr="Finnois" name_de="Finnisch" name_nl="Fins" name_sv="Finska" />
<lang code="fr" name_en="French" name_fr="Fran&amp;ccedil;ais" name_de="Franzosisch" name_nl="Frans" name_sv="Franska" />
<lang code="it" name_en="Italian" name_fr="Italien" name_de="Italienisch" name_nl="Italiaans" name_sv="Italiensk" />
<lang code="is" name_en="Icelandic" name_fr="Islandais" name_de="Isl&amp;auml;ndisch" name_nl="IJslands" name_sv="Isl&amp;auml;ndska" />
<lang code="nl" name_en="Dutch" name_fr="Neerlandais" name_de="Hollandisch" name_nl="Nederlands" name_sv="Holl&amp;auml;ndska" />
<lang code="no" name_en="Norwegian" name_fr="Norvegien" name_de="Norwegisch" name_nl="Noors" name_sv="Norska" />
<lang code="pl" name_en="Polish" name_fr="Polonais" name_de="Polnisch" name_nl="Pools" name_sv="Polska" />
<lang code="pt" name_en="Portuguese" name_fr="Portugais" name_de="Portugiesisch" name_nl="Portugees" name_sv="Portugisiska" />
<lang code="sv" name_en="Swedish" name_fr="Suedois" name_de="Schwedisch" name_nl="Zweeds" name_sv="Svenska" />
</languages>
